# Generated by Django 4.0 on 2022-05-07 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('parent', models.CharField(choices=[('1', 'TOP'), ('2', 'BOTTOM'), ('3', 'CLOTHING'), ('4', 'ACCESSORIES')], default=3, max_length=1, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='Product/%Y/%m/%d')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('old_price', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pub_date', models.DateField(auto_now=True)),
                ('watch', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.status')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
