# Generated by Django 4.0 on 2022-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='OURTEAM/%m/%d')),
                ('description', models.TextField()),
                ('site', models.URLField()),
                ('position', models.CharField(choices=[('1', 'DIRECTOR'), ('2', 'MENEDJER'), ('3', 'WEB DEVELOPER'), ('4', 'DESING'), ('5', 'BACK END DEVELOPER')], default='3', max_length=1)),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
