# Generated by Django 4.0 on 2022-05-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_team_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(choices=[('DIRECTOR', 'DIRECTOR'), ('DIRECTOR', 'MENEDJER'), ('WEB DEVELOPER', 'WEB DEVELOPER'), ('DESING', 'DESING'), ('BACK END DEVELOPER', 'BACK END DEVELOPER')], default='WEB DEVELOPER', max_length=50),
        ),
    ]
