# Generated by Django 4.0.4 on 2022-05-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_count'),
        ('main', '0004_alter_team_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
