# Generated by Django 4.0.4 on 2022-05-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_category_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('cart', models.ManyToManyField(null=True, related_name='carts', to='product.product')),
                ('wishlist', models.ManyToManyField(null=True, related_name='wishlists', to='product.product')),
            ],
        ),
    ]
