# Generated by Django 4.0.4 on 2022-05-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_count'),
        ('user', '0002_alter_myuser_cart_alter_myuser_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='carts', to='product.product'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='product.product'),
        ),
    ]
